In [1]:
import numpy as np

In [6]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = a.reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
c = b.flatten()

In [15]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
d = b.flatten(order='F')
d

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [33]:
arr = np.random.randint(20, size=(3,4))
arr

array([[ 7, 15,  3,  4],
       [ 0,  4, 18, 13],
       [ 5, 12,  7,  5]])

In [34]:
arr.shape

(3, 4)

In [35]:
t_arr = np.transpose(arr)
t_arr

array([[ 7,  0,  5],
       [15,  4, 12],
       [ 3, 18,  7],
       [ 4, 13,  5]])

In [36]:
t_arr.shape

(4, 3)

In [39]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
b = np.array([10, 10, 10])

In [41]:
c = np.add(a, b)
c

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [42]:
np.multiply(a, b)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [43]:
np.divide(a, b)

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [44]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a[:5]

array([0, 1, 2, 3, 4])

In [46]:
a[6:]

array([6, 7, 8, 9])

In [47]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [48]:
s = slice(2, 10, 2)
a[s]

array([2, 4, 6, 8])

In [55]:
arr = np.arange(5, 50, 5).reshape(3, 3)
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
for x in np.nditer(arr):
    print(x)

5
10
15
20
25
30
35
40
45
