In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [3]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
b.shape

(2, 4)

In [11]:
c = np.arange(1,9).reshape(2, 4)

In [12]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
d = b * c
d

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [14]:
e = b + c
e

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [20]:
arr = np.random.randint(50, size=(3, 4))
arr

array([[46, 27, 32, 35],
       [19,  8,  1, 41],
       [36, 25,  5, 36]])

In [21]:
arr.ndim

2

In [22]:
len(arr)

3

In [23]:
type(arr)

numpy.ndarray

In [26]:
arr[0][1]

27

In [29]:
arr.itemsize

4

In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]], dtype=np.float64)
arr

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [36]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
print(np.char.capitalize('hello world'))

Hello world


In [40]:
print(np.char.add('hello', ' world'))

hello world


In [42]:
print(np.char.add(['hello', 'how'], [' world', ' are you?']))

['hello world' 'how are you?']


In [43]:
print(np.char.title('I am fine'))

I Am Fine


In [45]:
print(np.char.lower('HELLO'))

hello


In [46]:
print(np.char.upper('python'))

PYTHON


In [47]:
print(np.char.split('I am studying data science'))

['I', 'am', 'studying', 'data', 'science']


In [49]:
print(np.char.splitlines('Today is\nMonday'))

['Today is', 'Monday']


In [55]:
print(np.char.strip(['python', 'moon', 'goon'], 'on'))

['pyth' 'm' 'g']


In [56]:
print(np.char.join(':', 'abc'))

a:b:c


In [57]:
print(np.char.replace('He is gone', 'is', 'was'))

He was gone
